server:
  port: 8080
  connection-timeout: 20000
  servlet:
    display-name: ApiGateway
    context-path: /api

spring:
  task:
    execution:
      pool:
        core-size: 8
        max-size: 10
        queue-capacity: 1000
  data:
    mongodb:
      database: "api"

resources: .
logging:
  file: ${resources}/logs/gitlab.log
  path: ${resources}/logs
  level:
    ROOT: DEBUG
